apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
        version: v1
    spec:
      containers:
      - name: app
        image: ghcr.io/xword/go-go-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: APP_VERSION
          value: "v1.0"
        - name: APP_COLOR
          value: "green"
